(ns valip.test-valip
        (:require [clojure.test :refer :all])
                                                                           
                                        )

(deftest test-foo
  (testing "Testing the dummy function."
    (is true)))

;;;;;;;;;;;; This file autogenerated from test/cljx/valip/test-valip.cljx
