(ns valip.test.core
  (:use [valip.core :only [validation-on validate]])
                          
        (:require-macros [cemerick.cljs.test :refer [deftest is]])
        (:require [cemerick.cljs.test :as t]))

(deftest validation-on-test
  (let [p? (fn [x] false)
        v  (validation-on :x p? "error")]
    (is (= (v {:x 1}) {:x ["error"]}))))

(deftest validate-test
  (is (= (validate {:x 17}
           [:x (complement nil?) "must be present"]
           [:y (complement nil?) "must be present"]
           [:x #(> % 18) "must be greater than 18"])
         {:x ["must be greater than 18"]
          :y ["must be present"]})))

;;;;;;;;;;;; This file autogenerated from test/cljx/valip/test/core.cljx
