(ns valip.test-valip
                                             
         (:require-macros [cemerick.cljs.test :refer [deftest testing is]])
         (:require [cemerick.cljs.test]))

(deftest test-foo
  (testing "Testing the dummy function."
    (is true)))

;;;;;;;;;;;; This file autogenerated from test/cljx/valip/test-valip.cljx
